//
//  MovieDetailInteractorTests.swift
//  Movie
//
//  Created by Thibault Ballof on 18/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movie
import XCTest

class MovieDetailInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MovieDetailInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMovieDetailInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMovieDetailInteractor() {
    sut = MovieDetailInteractor()
    sut.movie =  Movie(backdropPath: "", title: "Dune 2", posterPath: "", releaseDate: "", overview: "")
  }
  
  // MARK: Test doubles
  
  class MovieDetailPresentationLogicSpy: MovieDetailPresentationLogic, MovieDetailDataStore{
    var presentSomethingCalled = false
      var movie: Movie?
      func presentMovieDetail(response: MovieDetail.FetchMovie.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething() {
    // Given
    let spy = MovieDetailPresentationLogicSpy()
    sut.presenter = spy
      let request = MovieDetail.FetchMovie.Request()
    
    // When

    sut.fetchMovie(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
