//
//  MovieDetailPresenterTests.swift
//  Movie
//
//  Created by Thibault Ballof on 18/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movie
import XCTest

class MovieDetailPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MovieDetailPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMovieDetailPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMovieDetailPresenter()
  {
    sut = MovieDetailPresenter()
  }
  
  // MARK: Test doubles
  
  class MovieDetailDisplayLogicSpy: MovieDetailDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: MovieDetail.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = MovieDetailDisplayLogicSpy()
    sut.viewController = spy
    let response = MovieDetail.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
