//
//  MovieListWorker.swift
//  Movie
//
//  Created by Thibault Ballof on 17/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MovieListWorker {
    
    let service: Networking
    
    init(service: Networking) {
        self.service = service
    }
    
    func getMoviesList() async throws -> MoviesResults {
        do {
            return try await service.fetch(type: MoviesResults.self)
        } catch {
            throw error
        }
    }
}
