//
//  MovieListPresenter.swift
//  Movie
//
//  Created by Thibault Ballof on 17/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListPresentationLogic {
  func presentMovieList(response: MovieList.FetchMoviesList.Response)
}

class MovieListPresenter: MovieListPresentationLogic {
  weak var viewController: MovieListDisplayLogic?
  
  // MARK: Do something
  
  func presentMovieList(response: MovieList.FetchMoviesList.Response) {
      let viewModel = MovieList.FetchMoviesList.ViewModel(movies: response.movieList.results)
    viewController?.displayMovieList(viewModel: viewModel)
  }
}
