//
//  MovieListRouter.swift
//  Movie
//
//  Created by Thibault Ballof on 17/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieListRoutingLogic {
    func routeToMovieDetail(index: Int)
}

protocol MovieListDataPassing {
    var dataStore: MovieListDataStore? { get }
}

class MovieListRouter: NSObject, MovieListRoutingLogic, MovieListDataPassing {
    weak var viewController: MovieListViewController?
    var dataStore: MovieListDataStore?
    
    // MARK: Routing
    func routeToMovieDetail(index: Int) {
        let destinationVC = MovieDetailViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToMovieDetail(source: dataStore!, destination: &destinationDS, index: index)
        navigateToMovieDetail(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: Navigation
    
    func navigateToMovieDetail(source: MovieListViewController, destination: MovieDetailViewController) {
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToMovieDetail(source: MovieListDataStore, destination: inout MovieDetailDataStore, index: Int) {
        destination.movie = source.movieList?.results[index]
    }
}

