//
//  MovieListInteractorTests.swift
//  Movie
//
//  Created by Thibault Ballof on 18/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movie
import XCTest

class MovieListInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MovieListInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMovieListInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMovieListInteractor()
  {
    sut = MovieListInteractor()
  }
  
  // MARK: Test doubles
  
  class MovieListPresentationLogicSpy: MovieListPresentationLogic
  {
    var presentSomethingCalled = false
    
      func presentMovieList(response: MovieList.FetchMoviesList.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
    func testDoSomething() async
  {
    // Given
    let spy = MovieListPresentationLogicSpy()
    sut.presenter = spy
      let request = MovieList.FetchMoviesList.Request()
    
    // When
      await sut.fetchMoviesList(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
