//
//  MovieListViewControllerTests.swift
//  Movie
//
//  Created by Thibault Ballof on 18/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movie
import XCTest

class MovieListViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MovieListViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupMovieListViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMovieListViewController() {
    sut =  MovieListViewController()
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class MovieListBusinessLogicSpy: MovieListBusinessLogic {
    
    var doSomethingCalled = false
    
      func fetchMoviesList(request: MovieList.FetchMoviesList.Request) async {
        doSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testShouldDoSomethingWhenViewIsLoaded()
  {
    // Given
    let spy = MovieListBusinessLogicSpy()
    sut.interactor = spy
    
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
  }
  
  func testDisplaySomething()
  {
    // Given
      let viewModel = MovieList.FetchMoviesList.ViewModel(movies: []) // add mock data
    
    // When
    loadView()
    sut.displayMovieList(viewModel: viewModel)
    
    // Then
    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
  }
}
