//
//  MovieListPresenterTests.swift
//  Movie
//
//  Created by Thibault Ballof on 18/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movie
import XCTest

class MovieListPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: MovieListPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupMovieListPresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupMovieListPresenter()
    {
        sut = MovieListPresenter()
    }
    
    // MARK: Test doubles
    
    class MovieListDisplayLogicSpy: MovieListDisplayLogic {
        var displaySomethingCalled = false
        
        func displayMovieList(viewModel: MovieList.FetchMoviesList.ViewModel) {
            displaySomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething() {
        // Given
        let spy = MovieListDisplayLogicSpy()
        sut.viewController = spy
        let response = MovieList.FetchMoviesList.Response(movieList: MoviesResults.init(results: []))
        
        // When
        sut.presentMovieList(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
