//
//  MovieDetailModels.swift
//  Movie
//
//  Created by Thibault Ballof on 17/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail {
  // MARK: Use cases
  
  enum Something {
    struct Request {
    }
    struct Response {
        var movie: Movie
    }
    struct ViewModel {
        var movie: Movie
    }
  }
}
