//
//  MovieDetailPresenter.swift
//  Movie
//
//  Created by Thibault Ballof on 17/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
  func presentMovieDetail(response: MovieDetail.FetchMovie.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic {
  weak var viewController: MovieDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentMovieDetail(response: MovieDetail.FetchMovie.Response) {
      let viewModel = MovieDetail.FetchMovie.ViewModel(movie: response.movie)
    viewController?.displayMovieDetail(viewModel: viewModel)
  }
}
