//
//  MovieDetailInteractor.swift
//  Movie
//
//  Created by Thibault Ballof on 17/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic
{
    func doSomething(request: MovieDetail.Something.Request)
}

protocol MovieDetailDataStore
{
    var movie: Movie? { get set }
}

class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore
{
    var presenter: MovieDetailPresentationLogic?
    var worker: MovieDetailWorker?
    var movie: Movie?
    
    // MARK: Do something
    
    func doSomething(request: MovieDetail.Something.Request)
    {
        worker = MovieDetailWorker()
        worker?.doSomeWork()
        guard let movie else { return }
        let response = MovieDetail.Something.Response(movie: movie)
        presenter?.presentSomething(response: response)
    }
}
